//! Sealed light-client verification KATs for [`jlvm_core::verify_mpt_proof`].
//!
//! The vectors in `tests/fixtures/test-sealed-proofs.json` are copied verbatim
//! from metakit `docs/mpt-spec/test-sealed-proofs.json` -- emitted by the REAL
//! Scala prover (`MerklePatriciaProver.provePath`) and byte-pinned by metakit
//! `MptSpecFixtureSuite`. They cover a tagged `Inclusion` plus the four `Absence`
//! terminal families: branch-missing-nibble, other-leaf, extension-divergence,
//! and the empty trie. Companion TS suite:
//! `packages/typescript-jlvm/tests/mpt-sealed-proofs.test.ts` (same fixture bytes,
//! same accept/reject assertions -- the Rust<->TS byte-parity contract).
//!
//! FOLLOW-UP (metakit fork PR): promote these to a first-class SDK differential
//! vector `shared/mpt_sealed_proof_test_vectors.json` generated by a metakit-side
//! generator (mirroring `OrdinalCatalogVectorGenerator`), so the sealed format
//! joins the cross-language `shared/*.json` contract instead of a copied fixture.

use jlvm_core::verify_mpt_proof;
use serde_json::Value;
use std::path::PathBuf;

fn load_fixture() -> Value {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests/fixtures/test-sealed-proofs.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {}", path.display(), e));
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn cases(doc: &Value) -> &Vec<Value> {
    doc["cases"].as_array().expect("cases array")
}

fn find<'a>(doc: &'a Value, name: &str) -> &'a Value {
    cases(doc)
        .iter()
        .find(|c| c["name"] == name)
        .unwrap_or_else(|| panic!("no KAT named '{name}'"))
}

/// Flip the first hex nibble of a lowercase-hex string so it no longer matches.
fn flip_first_hex(hex: &str) -> String {
    let mut chars: Vec<char> = hex.chars().collect();
    if let Some(c) = chars.first_mut() {
        *c = if *c == '0' { '1' } else { '0' };
    }
    chars.into_iter().collect()
}

/// Corrupt the first (deepest) witness commitment so its recomputed digest can
/// no longer bind: flip a hash field, or inject a bogus branch child.
fn corrupt_first_commitment(proof: &mut Value) {
    let node = &mut proof["witness"][0];
    let contents = node["contents"].as_object_mut().expect("contents object");
    if let Some(dd) = contents.get("dataDigest").and_then(|v| v.as_str()) {
        let flipped = flip_first_hex(dd);
        contents.insert("dataDigest".into(), Value::String(flipped));
    } else if let Some(cd) = contents.get("childDigest").and_then(|v| v.as_str()) {
        let flipped = flip_first_hex(cd);
        contents.insert("childDigest".into(), Value::String(flipped));
    } else {
        // Branch: flip a child hash, or inject one if the map is empty.
        let pd = contents
            .get_mut("pathsDigest")
            .and_then(|v| v.as_object_mut())
            .expect("pathsDigest object");
        if let Some(k) = pd.keys().next().cloned() {
            let v = pd.get(&k).and_then(|v| v.as_str()).unwrap().to_string();
            pd.insert(k, Value::String(flip_first_hex(&v)));
        } else {
            pd.insert("0".into(), Value::String("00".repeat(32)));
        }
    }
}

#[test]
fn accepts_every_sealed_kat() {
    let doc = load_fixture();
    assert_eq!(
        cases(&doc).len(),
        5,
        "expected inclusion + 4 absence families"
    );
    for c in cases(&doc) {
        let name = c["name"].as_str().unwrap();
        let root = c["rootHash"].as_str().unwrap();
        assert!(
            verify_mpt_proof(root, &c["proof"]),
            "KAT '{name}' should verify against its root"
        );
    }
}

#[test]
fn untagged_legacy_inclusion_still_verifies() {
    // The legacy un-tagged `{path, witness}` shape must be treated as inclusion.
    let doc = load_fixture();
    let mut proof = find(&doc, "inclusion-tagged")["proof"].clone();
    proof.as_object_mut().unwrap().remove("type");
    let root = find(&doc, "inclusion-tagged")["rootHash"].as_str().unwrap();
    assert!(
        verify_mpt_proof(root, &proof),
        "un-tagged inclusion must verify"
    );
}

#[test]
fn rejects_wrong_root() {
    let doc = load_fixture();
    for c in cases(&doc) {
        let name = c["name"].as_str().unwrap();
        let bad_root = flip_first_hex(c["rootHash"].as_str().unwrap());
        assert!(
            !verify_mpt_proof(&bad_root, &c["proof"]),
            "KAT '{name}' must reject a wrong root"
        );
    }
}

#[test]
fn rejects_type_confusion() {
    // Reading an Inclusion proof as Absence (or vice-versa) must fail: the two
    // arms share the fold but have incompatible terminal assertions.
    let doc = load_fixture();
    for c in cases(&doc) {
        let name = c["name"].as_str().unwrap();
        let root = c["rootHash"].as_str().unwrap();
        let mut proof = c["proof"].clone();
        let flipped = match proof["type"].as_str().unwrap() {
            "Absence" => "Inclusion",
            _ => "Absence",
        };
        proof["type"] = Value::String(flipped.into());
        assert!(
            !verify_mpt_proof(root, &proof),
            "KAT '{name}' must reject a flipped type tag"
        );
    }
}

#[test]
fn rejects_unknown_type() {
    let doc = load_fixture();
    let root = find(&doc, "absence-branch-missing-nibble")["rootHash"]
        .as_str()
        .unwrap();
    let mut proof = find(&doc, "absence-branch-missing-nibble")["proof"].clone();
    proof["type"] = Value::String("Bogus".into());
    assert!(!verify_mpt_proof(root, &proof), "unknown type must reject");
}

#[test]
fn rejects_absence_of_a_present_key() {
    // The `absence-other-leaf` witness proves "abce" absent; the SAME witness must
    // NOT prove absence of "abcd", the key actually occupying that leaf.
    let doc = load_fixture();
    let c = find(&doc, "absence-other-leaf");
    let root = c["rootHash"].as_str().unwrap();
    let mut proof = c["proof"].clone();
    proof["path"] = Value::String("abcd".into());
    assert!(
        !verify_mpt_proof(root, &proof),
        "must not prove absence of a present key"
    );
}

#[test]
fn rejects_corrupted_witness() {
    let doc = load_fixture();
    for c in cases(&doc) {
        let name = c["name"].as_str().unwrap();
        let root = c["rootHash"].as_str().unwrap();
        let mut proof = c["proof"].clone();
        corrupt_first_commitment(&mut proof);
        assert!(
            !verify_mpt_proof(root, &proof),
            "KAT '{name}' must reject a corrupted terminal commitment"
        );
    }
}

#[test]
fn rejects_malformed_proof() {
    // Total on garbage input: never panics, always `false`.
    assert!(!verify_mpt_proof("00", &Value::Null));
    assert!(!verify_mpt_proof(
        "00",
        &serde_json::json!({ "path": "a1" })
    ));
    assert!(!verify_mpt_proof(
        "00",
        &serde_json::json!({ "type": "Absence", "path": "a1", "witness": [] })
    ));
}
