//! Cross-language conformance for the ordinal-catalog attestation verifier.
//!
//! Loads `shared/ordinal_catalog_test_vectors.json` (generated by the Scala
//! reference `OrdinalCatalogVectorGenerator`) and asserts that this crate's
//! `verify_ordinal_catalog_proof` reproduces every `expected` attestation/error
//! EXACTLY. Companion to the TypeScript `ordinal-catalog-vectors.test.ts`.

use jlvm_core::ordinal_catalog::{epoch_key, hot_epochs_key, ordinal_key, sealed_epochs_key};
use jlvm_core::verify_ordinal_catalog_proof;
use std::path::PathBuf;

#[test]
fn catalog_keys_match_reference() {
    assert_eq!(hot_epochs_key(), "bf219127ab671805b4bc75df3598e2db17eef5fab73facc3757e6baa8c416636");
    assert_eq!(sealed_epochs_key(), "19ab634f4720ce035b017e7ffb8e8ca5a4481e62309a5beffaf75da167ee1202");
    assert_eq!(ordinal_key(0), "c0020bf0613f2c15579e2e827e436cc0b445b6c2e2ee8f08922016e27c3d7be2");
    assert_eq!(epoch_key(0), "402a33e021e6fd2d8fb109ce145fef5df03a39a4d5e2f4f993fc812f79ca4692");
}

#[test]
fn ordinal_catalog_vectors_match_reference() {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // rust/jlvm-core -> repo root -> shared/...
    path.pop();
    path.pop();
    path.push("shared/ordinal_catalog_test_vectors.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {}", path.display(), e));
    let doc: serde_json::Value = serde_json::from_str(&text).expect("vectors are valid JSON");

    let epoch_size = doc["epochSize"].as_u64().expect("epochSize");
    let catalog_root = doc["catalogRoot"].as_str().expect("catalogRoot");
    let cases = doc["cases"].as_array().expect("cases array");

    let mut passed = 0usize;
    let mut failures: Vec<String> = Vec::new();
    for c in cases {
        let ordinal = &c["ordinal"];
        let expected = &c["expected"];
        let result = verify_ordinal_catalog_proof(catalog_root, &c["proof"], epoch_size)
            .unwrap_or_else(|e| panic!("ordinal {ordinal}: verifier errored: {e}"));
        let actual = result.to_expected_json();
        if &actual == expected {
            passed += 1;
        } else {
            failures.push(format!("ordinal {ordinal}: expected {expected}, got {actual}"));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} ordinal-catalog cases failed:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
    println!("ordinal-catalog differential: {}/{} cases passed", passed, cases.len());
}
