import fs from 'fs';
import path from 'path';

import { verifyMptProof } from '../src/index';

/**
 * Sealed light-client verification KATs for `verifyMptProof`.
 *
 * `tests/fixtures/test-sealed-proofs.json` is copied verbatim from metakit
 * `docs/mpt-spec/test-sealed-proofs.json` -- emitted by the REAL Scala prover
 * (`MerklePatriciaProver.provePath`) and byte-pinned by metakit
 * `MptSpecFixtureSuite`. It covers a tagged `Inclusion` plus the four `Absence`
 * terminal families (branch-missing-nibble, other-leaf, extension-divergence,
 * empty-trie). Companion Rust suite: `rust/jlvm-core/tests/mpt_sealed_proofs.rs`
 * (same fixture bytes, same accept/reject assertions -- the Rust<->TS byte-parity
 * contract).
 *
 * FOLLOW-UP (metakit fork PR): promote these to a first-class SDK differential
 * vector `shared/mpt_sealed_proof_test_vectors.json` generated by a metakit-side
 * generator (mirroring `OrdinalCatalogVectorGenerator`), so the sealed format
 * joins the cross-language `shared/*.json` contract instead of a copied fixture.
 */

interface SealedCase {
  name: string;
  rootHash: string;
  record?: unknown;
  proof: { type?: string; path: string; witness: unknown[] };
}
interface SealedVectors {
  description: string;
  cases: SealedCase[];
}

const fixturePath = path.join(__dirname, 'fixtures', 'test-sealed-proofs.json');
const vectors: SealedVectors = JSON.parse(fs.readFileSync(fixturePath, 'utf-8'));

const byName = (name: string): SealedCase => {
  const c = vectors.cases.find((x) => x.name === name);
  if (c === undefined) {
    throw new Error(`no KAT named '${name}'`);
  }
  return c;
};

/** Flip the first hex nibble of a lowercase-hex string so it no longer matches. */
const flipFirstHex = (hex: string): string => (hex[0] === '0' ? '1' : '0') + hex.slice(1);

/** Deep-clone a proof so a mutation can't leak between assertions. */
const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T;

/** Corrupt the first (deepest) witness commitment so its digest can't bind. */
const corruptFirstCommitment = (proof: SealedCase['proof']): void => {
  const contents = (proof.witness[0] as { contents: Record<string, unknown> }).contents;
  if (typeof contents.dataDigest === 'string') {
    contents.dataDigest = flipFirstHex(contents.dataDigest);
  } else if (typeof contents.childDigest === 'string') {
    contents.childDigest = flipFirstHex(contents.childDigest);
  } else {
    const pd = contents.pathsDigest as Record<string, string>;
    const keys = Object.keys(pd);
    if (keys.length > 0) {
      pd[keys[0]] = flipFirstHex(pd[keys[0]]);
    } else {
      pd['0'] = '00'.repeat(32);
    }
  }
};

describe('Sealed Merkle-Patricia light-client verification (KATs)', () => {
  it('has the inclusion + 4 absence families', () => {
    expect(vectors.cases.length).toBe(5);
  });

  it('accepts every sealed KAT against its root', () => {
    for (const c of vectors.cases) {
      expect({ name: c.name, ok: verifyMptProof(c.rootHash, c.proof) }).toEqual({
        name: c.name,
        ok: true,
      });
    }
  });

  it('treats an un-tagged legacy {path, witness} proof as inclusion', () => {
    const c = byName('inclusion-tagged');
    const untagged = clone(c.proof);
    delete untagged.type;
    expect(verifyMptProof(c.rootHash, untagged)).toBe(true);
  });

  it('rejects a wrong root for every KAT', () => {
    for (const c of vectors.cases) {
      expect({ name: c.name, ok: verifyMptProof(flipFirstHex(c.rootHash), c.proof) }).toEqual({
        name: c.name,
        ok: false,
      });
    }
  });

  it('rejects type confusion (Inclusion<->Absence) for every KAT', () => {
    for (const c of vectors.cases) {
      const proof = clone(c.proof);
      proof.type = proof.type === 'Absence' ? 'Inclusion' : 'Absence';
      expect({ name: c.name, ok: verifyMptProof(c.rootHash, proof) }).toEqual({
        name: c.name,
        ok: false,
      });
    }
  });

  it('rejects an unknown proof type', () => {
    const c = byName('absence-branch-missing-nibble');
    const proof = clone(c.proof);
    proof.type = 'Bogus';
    expect(verifyMptProof(c.rootHash, proof)).toBe(false);
  });

  it('does not prove absence of a present key', () => {
    // `absence-other-leaf` proves "abce" absent; the SAME witness must NOT prove
    // absence of "abcd", the key actually occupying that leaf.
    const c = byName('absence-other-leaf');
    const proof = clone(c.proof);
    proof.path = 'abcd';
    expect(verifyMptProof(c.rootHash, proof)).toBe(false);
  });

  it('rejects a corrupted terminal commitment for every KAT', () => {
    for (const c of vectors.cases) {
      const proof = clone(c.proof);
      corruptFirstCommitment(proof);
      expect({ name: c.name, ok: verifyMptProof(c.rootHash, proof) }).toEqual({
        name: c.name,
        ok: false,
      });
    }
  });

  it('is total on malformed input (never throws, always false)', () => {
    expect(verifyMptProof('00', null)).toBe(false);
    expect(verifyMptProof('00', { path: 'a1' })).toBe(false);
    expect(verifyMptProof('00', { type: 'Absence', path: 'a1', witness: [] })).toBe(false);
  });
});
